version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    reviewers: 
      - "ingridTPires"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    allow:
      - dependency-name: "Z.EntityFramework.Extensions"
